---

- include_vars: group_vars/kube_cluster.yml

- name: Delete CatBpf results directory (if it exists)
  become: yes
  file:
    path: "{{ filebench_dir }}/catbpf_results"
    state: absent

- name: Create CatBpf results directory
  file:
    path: "{{ filebench_dir }}/catbpf_results"
    state: directory

- name: Create catbpf config file
  template:
    src: "templates/catbpf.yml.j2"
    dest: "{{ filebench_dir }}/catbpf.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode:  0644
  become: true

- name: Copy fileserver workload
  copy:
    src: ../../shared_files/fileserver.f
    dest: "{{ filebench_dir }}/fileserver.f"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode:  0644

- name: Start Dstat
  shell: screen -S "FILEBENCH_CAT_N_DSTAT_{{run_number}}" -d -m dstat --time --cpu --mem --net --disk --swap --output "{{ filebench_dir }}/catbpf_results/dstat.csv"

- name: Pause for 10 seconds
  pause:
    seconds: 10

- name: Running filebench (with CatBpf) [run={{run_number}}]
  docker_container:
    name: catbpf_filebench
    image: taniaesteves/filebench_catbpf:v2
    state: started
    recreate: yes
    detach: false
    pid_mode: host
    network_mode: host
    privileged: true
    volumes:
      - /lib/modules:/lib/modules:ro
      - /usr/src:/usr/src:ro
      - /sys/kernel/debug/:/sys/kernel/debug/:ro
      - /tmp/cataio:/tmp/cataio
      - "{{ filebench_dir }}/catbpf.yml:/usr/share/catbpf/conf/config.yaml:ro"
      - "{{ filebench_dir }}/catbpf_results:/catbpf_data"
      - "{{ filebench_dir }}/fileserver.f:/filebench/workloads/fileserver.f"
    entrypoint: "{{ catbpf_filebench_entrypoint_filter_tid if (filter_tid|bool == true) else catbpf_filebench_entrypoint }}"
  register: catbpf_container

- name: Pause for 10 seconds
  pause:
    seconds: 10

- name: Stop dstat
  shell: screen -X -S "FILEBENCH_CAT_N_DSTAT_{{run_number}}" quit
  ignore_errors: true

- assert:
    that:
      - "not catbpf_container.failed"
      - "catbpf_container.container.State.Status == 'exited'"

- name: Save logs
  shell: docker logs catbpf_filebench > "{{ filebench_dir }}/catbpf_results/docker_logs.txt" 2>&1

- shell: ls -lah {{ filebench_dir }}/catbpf_results/catbpf-trace.json
  when: catbpf_filewriter_enabled|bool == true
  become: yes
  ignore_errors: true
  register: trace_ls_size

- debug:
    msg: "{{trace_ls_size.stdout}}"
  when: catbpf_filewriter_enabled|bool == true
  ignore_errors: true

- shell: rm {{ filebench_dir }}/catbpf_results/catbpf-trace.json
  when: catbpf_filewriter_enabled|bool == true
  become: yes
  ignore_errors: true

- shell: (cd "{{ filebench_dir }}/catbpf_results"; find . -maxdepth 1 -type f) | cut -d'/' -f2
  register: files_to_copy

- name: Save results
  fetch:
    src: "{{ filebench_dir }}/catbpf_results/{{ file_item }}"
    dest: "final_cataio_results/filebench/{{cat_n_result_dir}}/run_{{run_number}}/"
    flat: yes
  with_items: "{{ files_to_copy.stdout_lines }}"
  loop_control:
    loop_var: file_item