---

- name: Prepare Setup
  hosts: master
  gather_facts: no
  roles:
    - { role: cataio/prepare_setup, tags: ['never', 'prepare_setup'] }

- name: Create PVs
  hosts: master
  gather_facts: no
  roles:
    - { role: cataio/create_pvs, tags: ['never', 'deploy_cataio', 'create_pvs'] }

- name: Create Cataio pipeline
  hosts: master
  gather_facts: no
  roles:
    - { role: cataio/create_pipeline, tags: ['never', 'deploy_cataio', 'create_pipeline'] }

- name: Import Kibana dashboards
  hosts: master
  gather_facts: no
  roles:
    - { role: cataio/import_dashboards, when: "run_all is defined and run_all == 'true'", tags: ['never', 'deploy_cataio', 'import_dashboards'] }

- name: Delete Cataio pipeline
  hosts: master
  gather_facts: no
  roles:
    - { role: cataio/delete_pipeline, tags: ['never', 'delete_cataio', 'delete_pipeline'] }

- name: Delete PVs
  hosts: master
  gather_facts: no
  roles:
    - { role: cataio/delete_pvs, tags: ['never', 'delete_cataio', 'delete_pvs'] }
