---

- hosts: master
  gather_facts: no
  roles:
    - { role: cataio/delete_pipeline,   tags: [ 'clean_cataio_pipeline' ] }
    - { role: cataio/delete_pvs,        tags: [ 'clean_cataio_pipeline' ], run_all: 'true' }
    - { role: cataio/create_pvs,        tags: [ 'clean_cataio_pipeline' ], run_all: 'true'  }
    - { role: cataio/create_pipeline,   tags: [ 'clean_cataio_pipeline' ], run_all: 'true' }
    - { role: cataio/import_dashboards, tags: [ 'clean_cataio_pipeline' ]  }
  tags:
    - always

- hosts: all
  become: yes
  gather_facts: no
  tasks:
  - name: Clearing the cache
    shell: sync; echo 3 > /proc/sys/vm/drop_caches
    register: caches_clean
  tags:
    - always

- name: Cataio (CatBpf + "{{ groups['node'] | length }}" ES)
  hosts: test
  gather_facts: no
  become: no
  roles:
    - { role: filebench/catbpf_new, when: caches_clean, tags: ['never', 'cataio'], catbpf_eswriter_enabled: true, catbpf_filewriter_enabled: false, catbpf_events: ["all"], catbpf_wait_timeout: -1, cat_n_result_dir: "cataio_{{ groups['node'] | length }}_es", catbpf_prof_on: true }

- name: Cataio (CatBpf + "{{ groups['node'] | length }}" ES, filter_by_tid)
  hosts: test
  gather_facts: no
  become: no
  roles:
    - { role: filebench/catbpf_new, when: caches_clean, tags: ['never','cataio_filter_tid'], catbpf_eswriter_enabled: true, catbpf_filewriter_enabled: false, catbpf_events: ["all"], catbpf_wait_timeout: -1, cat_n_result_dir: "cataio_{{ groups['node'] | length }}_es_filter_tid", filter_tid: true, catbpf_prof_on: true }


- name: Cataio (CatBpf + "{{ groups['node'] | length }}" ES, events=stat)
  hosts: test
  gather_facts: no
  become: no
  roles:
    - { role: filebench/catbpf_new, when: caches_clean, tags: ['never','cataio_filter_stat'], catbpf_eswriter_enabled: true, catbpf_filewriter_enabled: false, catbpf_events: ["stat"], catbpf_wait_timeout: -1, cat_n_result_dir: "cataio_{{ groups['node'] | length }}_es_filter_stat", catbpf_prof_on: true }

- name: Cataio (CatBpf + "{{ groups['node'] | length }}" ES, events=read)
  hosts: test
  gather_facts: no
  become: no
  roles:
    - { role: filebench/catbpf_new, when: caches_clean, tags: ['never','cataio_filter_read'], catbpf_eswriter_enabled: true, catbpf_filewriter_enabled: false, catbpf_events: ["read"], catbpf_wait_timeout: -1, cat_n_result_dir: "cataio_{{ groups['node'] | length }}_es_filter_read", catbpf_prof_on: true }

- name: Cataio (CatBpf + "{{ groups['node'] | length }}" ES, profiling ON)
  hosts: test
  gather_facts: no
  become: no
  roles:
    - { role: filebench/catbpf_new, when: caches_clean, tags: ['never','cataio_filter_read'], catbpf_eswriter_enabled: true, catbpf_filewriter_enabled: false, catbpf_events: ["all"], catbpf_wait_timeout: -1, cat_n_result_dir: "cataio_{{ groups['node'] | length }}_es_profiling", catbpf_prof_on: true, catbpf_prof_times: true }



# ---- old ---

- name: Cataio (CatBpf + "{{ groups['node'] | length }}" ES - flush_bytes=4MB)
  hosts: test
  gather_facts: no
  become: no
  roles:
    - { role: filebench/catbpf_new, when: caches_clean, tags: ['never', 'cataio_fb_4mb'], catbpf_eswriter_enabled: true, catbpf_filewriter_enabled: false, catbpf_events: ["all"], catbpf_wait_timeout: -1, cat_n_result_dir: "cataio_{{ groups['node'] | length }}_es_fb_4mb", catbpf_es_flush_bytes: 4194304 }

- name: Cataio (CatBpf + "{{ groups['node'] | length }}" ES - flush_interval=1min)
  hosts: test
  gather_facts: no
  become: no
  roles:
    - { role: filebench/catbpf_new, when: caches_clean, tags: ['never', 'cataio_fi_1m'], catbpf_eswriter_enabled: true, catbpf_filewriter_enabled: false, catbpf_events: ["all"], catbpf_wait_timeout: -1, cat_n_result_dir: "cataio_{{ groups['node'] | length }}_es_fi_1m", catbpf_es_flush_interval: 60 }

- name: Cataio (CatBpf + "{{ groups['node'] | length }}" ES - flush_bytes=10MB)
  hosts: test
  gather_facts: no
  become: no
  roles:
    - { role: filebench/catbpf_new, when: caches_clean, tags: ['never', 'cataio_fb_10mb'], catbpf_eswriter_enabled: true, catbpf_filewriter_enabled: false, catbpf_events: ["all"], catbpf_wait_timeout: -1, cat_n_result_dir: "cataio_{{ groups['node'] | length }}_es_fb_10mb", catbpf_es_flush_bytes: 10485760 }

- name: Cataio (CatBpf + "{{ groups['node'] | length }}" ES - flush_bytes=100MB)
  hosts: test
  gather_facts: no
  become: no
  roles:
    - { role: filebench/catbpf_new, when: caches_clean, tags: ['never', 'cataio_fb_100mb'], catbpf_eswriter_enabled: true, catbpf_filewriter_enabled: false, catbpf_events: ["all"], catbpf_wait_timeout: -1, cat_n_result_dir: "cataio_{{ groups['node'] | length }}_es_fb_100mb", catbpf_es_flush_bytes: 104857600, catbpf_es_flush_interval: 600 }

- name: Cataio (CatBpf + "{{ groups['node'] | length }}" ES - flush_bytes=15MB)
  hosts: test
  gather_facts: no
  become: no
  roles:
    - { role: filebench/catbpf_new, when: caches_clean, tags: ['never', 'cataio_fb_15mb'], catbpf_eswriter_enabled: true, catbpf_filewriter_enabled: false, catbpf_events: ["all"], catbpf_wait_timeout: -1, cat_n_result_dir: "cataio_{{ groups['node'] | length }}_es_fb_15mb", catbpf_es_flush_bytes: 15728640, catbpf_es_flush_interval: 600 }

- name: Cataio (CatBpf + "{{ groups['node'] | length }}" ES - flush_bytes=10MB, 10min)
  hosts: test
  gather_facts: no
  become: no
  roles:
    - { role: filebench/catbpf_new, when: caches_clean, tags: ['never', 'cataio_fb_10mb_10min'], catbpf_eswriter_enabled: true, catbpf_filewriter_enabled: false, catbpf_events: ["all"], catbpf_wait_timeout: -1, cat_n_result_dir: "cataio_{{ groups['node'] | length }}_es_fb_10mb_10min", catbpf_es_flush_bytes: 10485760, catbpf_es_flush_interval: 600, catbpf_prof_times: true  }




- name: Cataio (CatBpf + "{{ groups['node'] | length }}" ES - flush_bytes=30MB)
  hosts: test
  gather_facts: no
  become: no
  roles:
    - { role: filebench/catbpf_new, when: caches_clean, tags: ['never', 'cataio_fb_30mb'], catbpf_eswriter_enabled: true, catbpf_filewriter_enabled: false, catbpf_events: ["all"], catbpf_wait_timeout: -1, cat_n_result_dir: "cataio_{{ groups['node'] | length }}_es_fb_30mb", catbpf_es_flush_bytes: 31457280, catbpf_es_flush_interval: 600, catbpf_prof_times: true }


- name: Cataio (CatBpf + "{{ groups['node'] | length }}" ES - flush_bytes=5MB)
  hosts: test
  gather_facts: no
  become: no
  roles:
    - { role: filebench/catbpf_new, when: caches_clean, tags: ['never', 'cataio_fb_5mb'], catbpf_eswriter_enabled: true, catbpf_filewriter_enabled: false, catbpf_events: ["all"], catbpf_wait_timeout: -1, cat_n_result_dir: "cataio_{{ groups['node'] | length }}_es_fb_5mb", catbpf_es_flush_bytes: 5242880, catbpf_es_flush_interval: 600, catbpf_prof_times: true }
