---
- hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Clearing the cache
      shell: sync; echo 3 > /proc/sys/vm/drop_caches
      register: caches_clean
  tags:
    - always

- name: Vanilla
  hosts: test
  gather_facts: no
  become: no
  roles:
    - {
        role: tests/filebench/vanilla,
        when: caches_clean,
        tags: ["never", "vanilla"],
        setup_res_dir: "vanilla/t00_vanilla",
      }

# ------

# LTTng - overhead

- name: LTTng overhead - fs separated analysis
  hosts: test
  gather_facts: no
  become: no
  roles:
    - {
        role: tests/filebench/lttng-overhead,
        when: caches_clean,
        tags: ["never", "lttng_overhead_fs_post_analysis"],
        setup_res_dir: "lttng_overhead/t01_fs_post_analysis",
        lttng_live: false,
      }

- name: LTTng overhead - live separated analysis
  hosts: test
  gather_facts: no
  become: no
  roles:
    - {
        role: tests/filebench/lttng-overhead,
        when: caches_clean,
        tags: ["never", "lttng_overhead_live_post_analysis"],
        setup_res_dir: "lttng_overhead/t02_live_post_analysis",
      }

# ------

# babeltreace2 - overhead

- name: babeltrace2 overhead - stdout
  hosts: test
  gather_facts: no
  become: no
  roles:
    - {
        role: tests/filebench/lttng,
        when: caches_clean,
        tags: ["never", "babeltrace_overhead_stdout"],
        setup_res_dir: "babeltrace_overhead/t01_stdout",
        lttng_elk: false,
        babeltrace_vanilla: true
      }

- name: babeltrace2 overhead - write to /dev/null
  hosts: test
  gather_facts: no
  become: no
  roles:
    - {
        role: tests/filebench/lttng,
        when: caches_clean,
        tags: ["never", "babeltrace_overhead_discard"],
        setup_res_dir: "babeltrace_overhead/t02_discard",
        lttng_elk: false,
        babeltrace_vanilla: true,
        babeltrace_discard: true
      }

# ------

# elastic plugin - overhead

- name: elastic plugin overhead - write to /dev/null
  hosts: test
  gather_facts: no
  become: no
  roles:
    - {
        role: tests/filebench/lttng,
        when: caches_clean,
        tags: ["never", "elastic_overhead_discard"],
        setup_res_dir: "elastic_overhead/t01_discard",
        lttng_elk: false,
        babeltrace_discard: true
      }

- name: elastic plugin overhead - write to elasticsearch
  hosts: test
  gather_facts: no
  become: no
  roles:
    - {
        role: tests/filebench/lttng,
        when: caches_clean,
        tags: ["never", "elastic_overhead_elk"],
        setup_res_dir: "elastic_overhead/t02_elk",
      }