---


- name: Destroy Cataio Pipeline
  hosts: master
  gather_facts: no
  roles:
    - { role: cataio/delete_pipeline }
    - { role: cataio/delete_pvs,       run_all: 'true' }
  tags:
    - never
    - rebuild_cataio_pipeline
    - destroy_cataio_pipeline
    - catbpf

- name: Build Cataio Pipeline
  hosts: master
  gather_facts: no
  roles:
    - { role: cataio/create_pvs,       run_all: 'true' }
    - { role: cataio/create_pipeline,  run_all: 'true' }
    - { role: cataio/import_dashboards }
  tags:
    - never
    - rebuild_cataio_pipeline
    - catbpf

- name: Clear caches
  hosts: all
  become: yes
  gather_facts: no
  tasks:
  - name: Clearing the cache
    shell: sync; echo 3 > /proc/sys/vm/drop_caches
    register: caches_clean
  tags:
    - always

- name: Load
  hosts: test
  gather_facts: no
  become: no
  roles:
    - { role: rocksdb/load, when: caches_clean, tags: ['never','load'] }



- name: Vanilla
  hosts: test
  gather_facts: no
  become: no
  roles:
    - { role: rocksdb/vanilla, when: caches_clean, tags: ['never','vanilla'] }


- name: CatBpf
  hosts: test
  gather_facts: yes
  become: no
  roles:
    - { role: rocksdb/catbpf_new, when: caches_clean, tags: ['never','catbpf'], filter_paths: 'true', catbpf_events: ["open", "openat", "creat", "read", "pread64", "write", "pwrite64", "close", "fsync", "fdatasync"] }

- name: Strace
  hosts: test
  gather_facts: no
  become: no
  roles:
    - { role: rocksdb/strace, when: caches_clean, tags: ['never','strace'] }
