---

- name: Delete Kibana instance
  kubernetes.core.k8s:
    state: absent
    src: "{{ kube_cataio_dir }}/kibana.yml"
    wait: true

- name: Delete the Elasticsearch cluster
  kubernetes.core.k8s:
    state: absent
    src: "{{ kube_cataio_dir }}/elasticSearch.yml"
    wait: true

- name: Delete secret with Elastic credentials
  kubernetes.core.k8s:
    state: absent
    src: "{{ kube_cataio_dir }}/elasticCredentials.yml"
    wait: true